kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: nginx:latest
    volumeMounts:
        - name: volume
          mountPath: /data
          readOnly: false
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-pvc