# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
        key = "./terraform.tfstate"
        resource_group_name = "resource_group_name"
        storage_account_name = "storage_account_name"
        container_name = "prod"
  }
}
