apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: jenkins-service
spec:
  selector:
    app: jenkins-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
