# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: local-storage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jenkins-pv-volume
#   labels:
#     type: local
# spec:
#   storageClassName: local-storage
#   claimRef:
#     name: jenkins-pv-claim
#     namespace: default
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   local:
#     path: /mnt
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - aks-akspoolprd-14114758-vmss000000
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jenkins-pv-claim
#   namespace: default
# spec:
#   storageClassName: local-storage
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 3Gi
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-file-sc
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - mfsymlinks
  - nosharesock
  - actimeo=30
parameters:
  skuName: Standard_LRS
  location: eastus
  resourceGroup: 1-300bef38-playground-sandbox
  storageAccount: storageaccountguru2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
spec:
  storageClassName: azure-file-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
