apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-file-sc
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - mfsymlinks
  - nosharesock
  - actimeo=30
parameters:
  skuName: Standard_LRS
  location: westus
  resourceGroup: 1-f8b93685-playground-sandbox
  storageAccount: hubspokesacount0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
spec:
  storageClassName: azure-file-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi